const blogData = [{
    "title": "Decentralized social media app tutorial - Intro - By Aaron Smith",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/06\/decentralized-social-media-app-tutorial.html",
    "description": " <div class=\"row\">   <div class=\"col-md-6\"> <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/tsDgPRyKLlQ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>                 <\/div>      <div class=\"col-md-6\"><p>I thought this would be a great option for a tutorial:<\/p>                 <ul>          <li><a href=\"https:\/\/www.youtube.com\/playlist?list=PLxaq32Ptw4pnmS5Ff7xrcEThGL0uDbA1P\" target=\"_blank\">Tutorial Playlist<\/a><\/li>           <li><a href=\"https:\/\/github.com\/aaronrs2002\/social-media-tutorial\" target=\"_blank\">Github Link<\/a><\/li>        <\/ul> <ul><li>  1. Decentralized social media app \t<ul><li>A. News aggregate based on your news feed selections<\/li>\t<li>B. Easy to add and delete news feeds to your own profile<\/li>\t<li>C. Built in title search\/filter<\/li>      <\/ul>  <\/li><li>2. Social media web-app   <ul><li>A. Invite a network of friends<\/li>\t<li>B. Everyone shares their different news feeds<\/li>\t<li>C. Curate which stories you want by filtering out stories consisting of specific words<\/li>\t<li>D. Communicate with your network with the built in messenger<\/li>  <\/ul>    <\/li><li>3. Personalize your app   <ul>    <li>A. Banner updates<\/li>\t \t<li>B. Avatar updates<\/li>    <li>C. Choose from any \u201cBootswatch theme\u201d<\/li>  <\/ul>         <\/li><li>4. Your own private network. Works on any device. No App Store.  No contract.<\/li>        <\/ul>\t         <p><a href=\"https:\/\/youtu.be\/4QP8J0sY3iY\" target=\"_blank\">Link to the original demo video:<\/a><\/p>                  <p>Web-Presence LLC<\/p>                                                                                                   <\/div>     <\/div>",
    "pubDate": "Thu, 02 Jun 2022 20:20:00 ",
    "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-6647982402169492612"
},
{
    "title": "Point of Sale Tutorial Introduction - By: Aaron Smith - Web-Presence LLC",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/05\/point-of-sale-tutorial-introduction.html",
    "description": " <div class=\"row\">   <div class=\"col-md-6\"> <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/q6I5FM8K8U4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>       <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <p>Follow me through a basic introduction to writing a cart on the client side first. Along with a cart, we will build a Purchase Log, a Content Management System for inventory and Sales Analytics. In later tutorials we will take this cart to the next level using a database and secure login for multiple users.<\/p> <p><a href=\"https:\/\/www.youtube.com\/playlist?list=PLxaq32Ptw4pkHgzkOzkTkFJiVMp60iav-\" target=\"_blank\">Tutorial Playlist<\/a>  <\/p><p>Web-Presence LLC<\/p> <\/div>     <\/div>", "pubDate": "Tue, 17 May 2022 19:41:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-6903469115906963988"
},
{
    "title": "React.js Point of Sale Tutorial Part 7 - Integrate modules into framework  - By: Aaron Smith - Web-Presence LLC",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/05\/reactjs-point-of-sale-tutorial-part-7.html",
    "description": " <div class=\"row\">   <div class=\"col-md-6\"> <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/tlEcFFzXoSY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>       <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <p>This is the final video where we take the login framework from lesson 6 and combine it with our modules from lesson 5. We clear out all the local storage and replace it with api calls to our database.<\/p>                   <a href=\"https:\/\/github.com\/aaronrs2002\/cart-tutorial-7\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                          <\/div>     <\/div>", "pubDate": "Fri, 13 May 2022 00:08:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-5922617954388475099"
},
{
    "title": "React.js Point of Sale Tutorial Part 6 - Building a Login Framework - By: Aaron Smith - Web-Presence LLC", "link": "https:\/\/web-presence-news.blogspot.com\/2022\/05\/reactjs-point-of-sale-tutorial-part-6.html",
    "description": " <div class=\"row\">   <div class=\"col-md-6\"> <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/fdwgRxFuf6M\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>  <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <p>In this lesson we build the client-side and the server-side of a JSON Web Token login framework using Node.js for the server-side and React.js for the client-side. In future lessons we will be plugging web-apps we build into this secure framework.<\/p>             <a href=\"https:\/\/github.com\/aaronrs2002\/jwt-login-framework\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                          <\/div>     <\/div>", "pubDate": "Tue, 10 May 2022 13:32:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-8899803719711431048"
},
{
    "title": "React.js Point of Sale Tutorial Part 5 - Building analytics using Apex Charts - By: Aaron Smith - Web-Presence LLC", "link": "https:\/\/web-presence-news.blogspot.com\/2022\/04\/test.html",
    "description": " <div class=\"row\">   <div class=\"col-md-6\"> <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/w73lHenpOJs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>  <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <ul>          <li>Add quantity to item object<\/li>          <li>Modularize item selector<\/li>          <li>Modularize time selector<\/li>          <li>Filter purchases by user<\/li>          <li>Build Sales Analytics<\/li>          <li>Small bug fixes<\/li>        <\/ul>  <p>Follow me through a basic introduction to writing a cart on the client side first. Along with a cart, we will build a Purchase Log, a Content Management System for inventory and Sales Analytics.<\/p>  <p>In later tutorials we will take this cart to the next level using a database and secure login for multiple users.<\/p>        <a href=\"https:\/\/github.com\/aaronrs2002\/cart-tutorial-5\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                           <\/div>    <\/div>", "pubDate": "Wed, 27 Apr 2022 15:40:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-3892557557104752097"
},
{
    "title": "React.js Point of Sale Tutorial Part 4 - Building a CRUD Interface - By: Aaron Smith - Web-Presence LLC",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/04\/required-skills-to-complete-tutorial.html",
    "description": " <div class=\"row\">   <div class=\"col-md-6\">  <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/Ms4ugO7M4D4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>  <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <ul>          <li>Refactoring filter           <li>Build Content management System for \"inventory module\"<\/li>          <li>Front End Validation<\/li>          <li>Build data in local storage for prototyping (db comes in later episodes)<\/li>          <li>Build a CRUD (Create, Read, Update, Delete) interface<\/li>          <li>Update price variable<\/li>         <\/ul>  <p>Follow me through a basic introduction to writing a cart on the client side first. Along with a cart, we will build a Purchase Log, a Content Management System for inventory and Sales Analytics.<\/p>  <p>In later tutorials we will take this cart to the next level using a database and secure login for multiple users.<\/p>        <a href=\"https:\/\/github.com\/aaronrs2002\/cart-tutorial-4\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                           <\/div>    <\/div>", "pubDate": "Wed, 20 Apr 2022 00:41:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-8080495091039047359"
},
{
    "title": "React.js Point of Sale Tutorial Part 3 - Building Navigation - By: Aaron Smith - Web-Presence LLC",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/04\/reactjs-cart-tutorial-part-3-by-aaron.html",
    "description": " <div class=\"row\">       <div class=\"col-md-6\">  <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/QTXSJp9Hy2U\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>  <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <ul>                    <li>Refactor Counter<\/li>          <li>Offset Timestamp<\/li>          <li>Show alert function<\/li>          <li>Create nav bar<\/li>          <li>Active module persistence<\/li>          <li>Passing active module<\/li>        <\/ul> <p>Follow me through a basic introduction to writing a cart on the client side first. Along with a cart, we will build a Purchase Log, a Content Management System for inventory and Sales Analytics.<\/p>  <p>In later tutorials we will take this cart to the next level using a database and secure login for multiple users.<\/p>                 <a href=\"https:\/\/github.com\/aaronrs2002\/cart-tutorial-3\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                           <\/div>    <\/div>",
    "pubDate": "Mon, 18 Apr 2022 23:24:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-4201204691074271901"
},
{
    "title": "React.js Point of Sale Tutorial Part 2 - Building a Search - By: Aaron Smith - Web-Presence LLC",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/04\/reactjs-cart-tutorial-part-2-by-aaron.html",
    "description": " <div class=\"row\">        <div class=\"col-md-6\">  <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/3QgIKfOHrbg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>  <\/div>      <div class=\"col-md-6\">         <h3>Lesson Summary:<\/h3>        <ul>          <li>Filter\/Search products<\/li>          <li>Purchase log (local storage for prototyping phase, db comes in later episodes)<\/li>          <li>Toggle info boxes<\/li>          <li>More purchase log work<\/li>          <li>Filter\/Search purchase log<\/li>          <li>Matching timestamps           <li>Testing<\/li>        <\/ul> <p>Follow me through a basic introduction to writing a cart on the client side first. Along with a cart, we will build a Purchase Log, a Content Management System for inventory and Sales Analytics.<\/p>  <p>In later tutorials we will take this cart to the next level using a database and secure login for multiple users.<\/p>        <a href=\"  https:\/\/github.com\/aaronrs2002\/cart-tutorial-2\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                           <\/div>    <\/div>",
    "pubDate": "Thu, 14 Apr 2022 05:50:00 ", "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-7655996063934192741"
},
{
    "title": "React.js Point of Sale Tutorial Part 1 - Building a Cart - By: Aaron Smith Web-Presence LLC",
    "link": "https:\/\/web-presence-news.blogspot.com\/2022\/04\/reactjs-cart-tutorial.html",
    "description": " <div class=\"row\">        <div class=\"col-md-6\">  <iframe style=\"width: 100%; height: auto; min-height: 270px;\" src=\"https:\/\/www.youtube.com\/embed\/rAzzAqW5dhk\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>  <\/div>      <div class=\"col-md-6\">           <h3>Lesson Summary:<\/h3>        <ul>                  <li>Start with create-react-app<\/li>          <li>Mapping through inventory list<\/li>          <li>CSS Tricks<\/li>          <li>Add item<\/li>          <li>Build cart module<\/li>          <li>Cart items<\/li>          <li>Remove cart items<\/li>          <li>Calculate function<\/li>        <\/ul>         <h3>Required skills to complete tutorial:<\/h3>        <p>Basic JavaScript, React.js, React Hooks, CSS, Bootstrap 4 (using a Bootswatch theme), Font Awesome 5.8.2<\/p>  <p>Follow me through a basic introduction to writing a cart on the client side first. Along with a cart, we will build a Purchase Log, a Content Management System for inventory and Sales Analytics.<\/p>  <p>In later tutorials we will take this cart to the next level using a database and secure login for multiple users.<\/p>        <a href=\"https:\/\/github.com\/aaronrs2002\/cart-tutorial-1\" target=\"_blank\">Tutorial code link here.<\/a>                 <p>Web-Presence LLC<\/p>                                                                                           <\/div>    <\/div>",
    "pubDate": "Tue, 12 Apr 2022 17:31:00 ",
    "guid": "tag:blogger.com,1999:blog-8505796167510599349.post-4969300463499364959"
}];

let tempBlogHTML = "";

for (let i = 0; i < blogData.length; i++) {
    tempBlogHTML = tempBlogHTML + "<article id='postNum-" + blogData[i].guid + "'><div class='container'><div class='row'><div class='col-md-12'><h2>" + blogData[i].title + "</h2><hr><div>" + blogData[i].description + "</div><i>Published: " + blogData[i].pubDate + "</i></div></div></div> <div class='row'><div class='col-md-12'><a target='_blank' href='https://www.blogger.com/comment.g?blogID=" + blogData[i].guid + "&amp;'> Post comment: <i class='fas fa-bullhorn'></i></a></div></div></div></article>";
}

document.querySelector("[data-module='blog']").innerHTML = tempBlogHTML;