const localVars = [
    {

        blogUrls: [
            "",
            "/2025/01/manage-tasks-time-tracking-for.html",
            "/2025/01/explore-suite-of-open-source-javascript.html",
            "/2025/01/javascript-time-clock-from-reactjs-to.html",
            "/2024/12/free-web-developer-invoice-generator.html",
            "/2024/12/web-developer-invoicing-intro.html",
            "/2024/12/abstract-problem-solving-decouple.html",
            "/2024/11/front-end-framework-without-react-or.html",
            "/2024/11/reactjs-build-dynamic-hinting-feature.html",
            "/2024/10/javascript-tutorial-hijack-js-datepicker.html",
            "/2024/05/jwt-login-framework-2024-server-side.html",
            "/2024/04/javascript-weather-api-tutorial.html",
            "/2024/04/universally-unique-identifiers.html",
            "/2024/04/npsgov-api-javascript-developer-tutorial.html",
            "/2024/04/data-commons-and-javascript-turn-your.html",
            "/2024/04/javascript-texas-holdem-beta-testing.html",
            "/2024/04/javascript-bingo-upgrade-video.html",
            "/2024/03/hosting-nodejs-web-app-on-github.html",
            "/2024/03/hosting-nodejs-app-or-service-cors.html",
            "/2024/03/replace-react-run-nodejs-app-with.html",
            "/2024/03/apex-line-chart-tutorial-using-reactjs.html",
            "/2024/03/dynamic-html-forms-dom-manipulation.html",
            "/2024/02/wireframing-prototype-building-proof-of.html",
            "/2024/02/javascript-texas-holdem-update.html",
            "/2024/01/utilize-css-sprite-images-for.html",
            "/2024/01/javascript-form-validation-save-your.html",
            "/2024/01/client-side-theme-swapping-using.html",
            "/2024/01/use-chatgpt-to-upgrade-your-seo-search.html",
            "/2024/01/how-to-utilize-government-open-api.html",
            "/2023/12/using-reactjs-and-axios-to-build.html",
            "/2023/12/nearby-locations-javascript-reactjs-and.html",
            "/2023/11/coding-projects-using-open-source-city.html",
            "/2023/10/final-walk-through-reactjs-tutorial-9.html",
            "/2023/10/order-and-review-component-reactjs.html",
            "/2023/09/ordering-vs-purchasing-apex-chart-with.html",
            "/2023/09/reactjs-tutorial-6-from-cart-to-e.html",
            "/2023/09/reactjs-tutorial-5-from-cart-to-e-com.html",
            "/2023/08/reactjs-tutorial-4-from-cart-to-e.html",
            "/2023/08/reactjs-tutorial-3-from-cart-to-e.html",
            "/2023/08/reactjs-tutorial-2-from-cart-to-e.html",
            "/2023/08/reactjs-tutorial-1-from-cart-to-e.html",
            "/2023/07/javascript-read-analyze-bank-csvascii.html",
            "/2023/07/it-ticket-manager-workflow-platform-9.html",
            "/2023/07/ticket-management-system-reactjs.html",
            "/2023/06/build-save-and-print-professional.html",
            "/2023/06/tutorial-7.html",
            "/2023/06/ticket-management-system-reactjs_1.html",
            "/2023/06/ticket-management-system-reactjs.html",
            "/2023/05/ticket-management-system-reactjs.html",
            "/2023/05/reactjs-digital-workflow-application_17.html",
            "/2023/05/reactjs-digital-workflow-application.html",
            "/2023/04/reactjs-workflow-application-tutorial.html",
            "/2023/01/javascript-bingo-in-less-than-300-lines.html",
            "/2022/12/css-javascript-tutorial-3-multiple.html",
            "/2022/12/css-tutorial-custom-themes-with.html",
            "/2022/10/free-online-poker.html",
            "/2022/10/javascript-tutorial-poker-in-500-lines.html",
            "/2022/09/free-games-i-wrote.html",
            "/2022/09/javascript-word-game-overview.html",
            "/2022/06/decentralized-social-media-app-tutorial.html",
            "/2022/05/point-of-sale-tutorial-introduction.html",
            "/2022/05/reactjs-point-of-sale-tutorial-part-7.html",
            "/2022/05/reactjs-point-of-sale-tutorial-part-6.html",
            "/2022/04/test.html",
            "/2022/04/required-skills-to-complete-tutorial.html",
            "/2022/04/reactjs-cart-tutorial-part-3-by-aaron.html",
            "/2022/04/reactjs-cart-tutorial-part-2-by-aaron.html",
            "/2022/04/reactjs-cart-tutorial.html",
            "/2022/02/daily-habits-of-successful-people-brian.html",
            "/2021/02/techlead-things-i-wish-i-knew-when-i.html",
            "/2021/02/secret-to-recruiting-rockstar-software.html",
            "/2020/08/5-google-analytics-trends-to-watch-out.html",
            "/2020/04/advice-on-working-from-home.html",
            "/2019/12/the-days-of-redux-for-react.html",
            "/2019/07/creating-coding-tests-for-interviews.html",
            "/2015/08/google-is-taking-big-step-to-kill-off.html",
            "/2015/04/experimental-css-shaders-bring.html"],
        relay: "https://mechanized-aesthetics.net/php-relays/EmailRelay.php",
        blogIdentifier: "AIzaSyC88LHPtxkMn7kEfo1XntANrqxOWjwpenM",
        blogId: "8505796167510599349",
        examples: [

            {
                "name": "RV Park Administrator",
                "software": "Bootstrap/CSS, JWT-Login, MySQL, Node.js, Vanilla JavaScript",
                "thumb": "img/rvParkThumSm.jpg",
                "youTube": "bjPti0dY7jo",
                "details": "RV Park Administrator is a web app that works on any device.  Save, email, print & evaluate transaction records - Guest timelines - Current, past and waiting guest details - Legal Contracts - Electricity monitoring for each unit - Post any message to your public website",
                "gitHub": "https://github.com/aaronrs2002",
                "created": "2024"
            },

            {
                "name": "eCommerce Platform",
                "software": "Bootstrap/CSS, JWT-Login, MySQL, Node.js, React.js",
                "thumb": "img/ecommThumb.jpg",
                "youTube": "vNGmP2IxP6A",
                "details": "Sales & Ordering Analytics - Content Management System - JSON web token multi-user login - Sales review options - Inventory module - <a href='#' onClick='populateScreen(&#34uKp8-Y3SFwE&#34)' >View 2020 e-comm legacy version 1.0 here.</a>",
                "gitHub": "https://github.com/aaronrs2002/cart-ecomm-tutorial-9",
                "created": "2023"
            }, {
                "name": "Client Based Management System",
                "software": "Bootstrap/CSS, JWT-Login, MySQL, Node.js, React.js",
                "thumb": "img/clienbasedManagementSystemmThumbV2.jpg",
                "youTube": "vfpiaPv6dy0",
                "details": "Organize guests and employees, generate invoices, build a budget and timeline, organize a workflow and communicate with everyone. <a href='#' onClick='populateScreen(&#34YtIdekGIxrI&#34)' >Watch demo video 2.</a>",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2023"
            },


            {
                "name": "Point of Sale - Web App",
                "software": "React.js/Redux,Node.js, MongoDB, Bootstrap/CSS, JWT-Login",
                "thumb": "img/posThumb.jpg",
                "youTube": "XOqfLIvIrWw",
                "details": "Point of Sale Web Application includes Inventory, CMS, Analytics,  Data-Filter and Multi-User-Secure-Login.",
                "gitHub": "https://github.com/aaronrs2002",
                "created": "2020"
            },
            {
                "name": "Decentralized Social Media App",
                "software": "React.js Node.js, MySQL, PHP CSS/Bootstrap",
                "thumb": "img/socialMediaApp.jpg",
                "youTube": "4QP8J0sY3iY",
                "details": "Compile all your favorite RSS feeds into one place. Filter out stories that don't interest you. Share feed networks, recommend your favorite posts and message with friends.",
                "gitHub": "https://github.com/aaronrs2002/social-media-tutorial",
                "created": "2020"
            },
            {
                "name": "City Data Web App",
                "software": "JavaScript/React.js, CSS/Bootstrap, PHP-API",
                "thumb": "img/cityDataAppThumb.jpg",
                "youTube": "LdNmOeIJJNU",
                "details": "Explore hiking trails, points of interest, parks, bus stops and so much more utilizing your town's open source data: <a href='https://mechanized-aesthetics.net/TEST/react-city-data/' target='_blank'>click here to visit site</a>",
                "gitHub": "https://github.com/aaronrs2002",
                "created": "2020"
            },
            {
                "name": "Health Tracker",
                "software": "Bootstrap/CSS, JWT-Login, MySQL, Node.js, React.js",
                "thumb": "img/workoutAppThumb.jpg",
                "youTube": "5h0IGywR23s",
                "details": "Log and analyze your nutritional intake vs calories burned while monitoring your progress. Plus, learn from professional trainers.",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2021"
            },
            {
                "name": "Accounting Web App",
                "software": "Bootstrap/CSS, JWT-Login, MySQL, Node.js, React.js",
                "thumb": "img/balanceSheet.jpg",
                "youTube": "tTz-xUFpU54",
                "details": "Import Bank Files, Analyze Income and Expenses, Generate Work Orders, Track Hours on any device.",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2022"
            },
            {
                "name": "Content Management System",
                "software": "Bootstrap/CSS, JWT-Login, MySQL, Node.js, React.js",
                "thumb": "img/cmsThumb2021.jpg",
                "youTube": "b60EjnnN6Tc",
                "details": "Create unlimited pages. Choose from an array of media options. Unlimited banners for each page. Add a blog to any page. Add an event module to any page. Add an image carousel to any page. Choose from numerous themes. Works on any device.",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2021"
            },
            {
                "name": "Recipe Web App",
                "software": "React.js, Node.js, MongoDB, Bootstrap/CSS, Google-Oauth",
                "thumb": "img/recipeThumb.jpg",
                "youTube": "1Lw8QvlMfBY",
                "details": "Add, share and leave comment for your favorite recipes. All you need is a Gmail account.",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2019"
            },

            {
                "name": "Custom Homepage",
                "software": "React.js, Google-Firebase, Bootstrap/CSS, Authentication, PHP-Rest-API",
                "thumb": "img/customHomePageThumb.jpg",
                "youTube": "LSzs0jtbXpI",
                "details": "Custom Homepage Web App  - RSS feed API, YouTube API, weather API, custom themes, secure login, custom links with search filter, google calendar and responsive layout for all devices",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2019"
            },
            {
                "name": "Web Template with CMS",
                "software": "React.js, Google-Firebase, Bootstrap/CSS, Authentication, PHP-Rest-API",
                "thumb": "img/webTemplateThumb.jpg",
                "youTube": "pxmvfImaUH0",
                "details": "Content Management System with multiple layout options plus secure user login. Includes event app, blog, map, video, image carousel, Rich Text Editor, social media and contact components.  <a href='https://web-templates-6a6f1.web.app/?user=7IoD6zEANlVxeNeLw001O22k8JI2&' target='_blank'>Example User 1</a> , <a href='https://web-templates-6a6f1.web.app/?user=YRvF9srJvicNtiIqQ5nCmFD8YHt1&' target='_blank'>Example User 2</a>",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2019"
            },
            {
                "name": "Wedding App",
                "software": "React.js, Bootstrap/CSS, Node.js, JWT, MySQL",
                "thumb": "img/weddingAppThumb.jpg",
                "youTube": "yx-ImV5Nggw",
                "details": "Organize your special day while providing every detail to your friends and family.",
                "gitHub": "https://github.com/aaronrs2002/",
                "created": "2020"
            }, {
                "name": "Open source games",
                "software": "Vanilla JavaScript, Bootstrap/CSS",
                "thumb": "img/freeGamesThumb.jpg",
                "youTube": "MrsOwvHgW48",
                "details": "Discover a collection of free-to-play JavaScript games that require no installation or login! Play classics like Blackjack/21, Five-Card Draw Poker, Texas Hold'em Poker, Word Trivia, Bingo, and a Slot Machine. Accessible from any device. <a href='https://aaronrs2002.github.io/black-jack/' target='_blank' >Play free on gitHub.</a>",
                "gitHub": "https://github.com/aaronrs2002/black-jack",
                "created": "2023"
            }
        ],
        blocked: ["harshitb2712@gmail.com", "donfrenette@yahoo.com"],
    }]; 